#!/bin/bash

# Firebase 환경 변수 설정 도우미
echo "🔥 Firebase 환경 변수 설정 도우미"
echo "=================================="
echo ""
echo "Firebase Console에서 복사한 값들을 입력해주세요."
echo ""

# .env.local 파일 생성
ENV_FILE=".env.local"

echo "Firebase API Key를 입력하세요:"
read -r API_KEY

echo "Firebase Auth Domain을 입력하세요 (예: your-project.firebaseapp.com):"
read -r AUTH_DOMAIN

echo "Firebase Project ID를 입력하세요:"
read -r PROJECT_ID

echo "Firebase Storage Bucket을 입력하세요 (예: your-project.appspot.com):"
read -r STORAGE_BUCKET

echo "Firebase Messaging Sender ID를 입력하세요:"
read -r SENDER_ID

echo "Firebase App ID를 입력하세요:"
read -r APP_ID

echo "Firebase Measurement ID를 입력하세요 (예: G-XXXXXXXXXX):"
read -r MEASUREMENT_ID

# .env.local 파일 생성
cat > "$ENV_FILE" << EOF
# Firebase Configuration
# Generated by setup script

VITE_FIREBASE_API_KEY=$API_KEY
VITE_FIREBASE_AUTH_DOMAIN=$AUTH_DOMAIN
VITE_FIREBASE_PROJECT_ID=$PROJECT_ID
VITE_FIREBASE_STORAGE_BUCKET=$STORAGE_BUCKET
VITE_FIREBASE_MESSAGING_SENDER_ID=$SENDER_ID
VITE_FIREBASE_APP_ID=$APP_ID
VITE_FIREBASE_MEASUREMENT_ID=$MEASUREMENT_ID
EOF

echo ""
echo "✅ .env.local 파일이 생성되었습니다!"
echo ""
echo "다음 명령어로 개발 서버를 재시작하세요:"
echo "  npm run dev"
